services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    image: asthaprajapati21/frontend:latest
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    image: asthaprajapati21/backend:latest
    environment:
      MONGO_URL: mongodb://mongodb:27017/studentdb
    depends_on:
      - mongodb
    restart: unless-stopped

  mongodb:
    image: mongo:7
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data: